## Visualisations of extreme heatwaves generated by analogue based importance sampling
## Par Pascal Yiou (LSCE), Jan. 2019

NCEPdir="data/"
OUTdir=""


## Circulation reanalyses datasets (SLP, Z500, Z500 detrended)
## SLP: slp.1948-2018_NA.nc
## Z500: hgt.1948-2018_NA.nc
## Z500 detrended: base_z500_1950-01-01_2018-12-31_-80.0_50.0_20.0_70.0.nc
library(ncdf4)

source("_useful_functions.R")
source("_plotting_functions.R")

## Simulations
filesim="tx-m12d1_cal6_temp_0.75-test.Rdat"
varname="tx"

## Data recuperation
## Please get this data
filin = paste(NCEPdir,"hgt.1948-2018_NA.nc",sep="")
varana = "hgt"

## Circulation
nc = nc_open(filin)
datNCEP=lirevarnc(nc,varana)
dat.NCEP.dum=sousseasmean(datNCEP$dat,datNCEP$conv.time,l.year=c(1970:1999))
datNCEP$anom=dat.NCEP.dum$anom
datNCEP$seascyc=dat.NCEP.dum$seascyc
nc_close(nc)

## Temperature
#this can be replaced with other variable names.
filin = paste(NCEPdir,varname,"_FR_mean.nc",sep="")
nc = nc_open(filin)
varnc=nc$var[[varname]]
## Treatment of time
nctime = nc$dim[['time']]
time=nctime$vals
conv.time=caldat(time+julday(1,1,1950))
years=conv.time$year
months=conv.time$month
days=conv.time$day
T_day=ncvar_get(nc,varid=varnc)
nc_close(nc)
Date=10000*years+100*months+days

T=data.frame(Date,T_day)
## CSeasonal cycle calculation
mmdd = T$Date %% 10000


##for(filin in list.in){
print(paste("Processing",filesim))
load(paste('sim_data/',filesim,sep=''))

print(args_tmp)

varname = args_tmp[1] ## args_tmp is written with load(filin)!
Lsim =as.integer(args_tmp[2])
mo.start =as.integer(args_tmp[3])
day.start =as.integer(args_tmp[4])
nsim =as.integer(args_tmp[5])
yymin=as.integer(args_tmp[6])
yymax=as.integer(args_tmp[7])
jobid=args_tmp[9]

yy=yymin:yymax

## Seasonal cycle calculation
T.seascyc = tapply(T[[2]],mmdd,mean,na.rm=TRUE)

## First day of the season
idum=which(names(T.seascyc) == as.character(mo.start*100+1))

T.sum.sort=sort(unlist(simu.dyn$l.T.mean),
                    decreasing=TRUE,index.return=TRUE)
nyear = length(simu.dyn$l.T.mean)
## Special years selection:
## hottest, coldest, median and 2018
## If the hottest summer is 2018, show the second hottest
y1=ifelse(yy[T.sum.sort$ix[1]]==2015,2,1)
l.yref=c(2008, yy[unlist(simu.sta$l.T.mean) == min(unlist(simu.sta$l.T.mean))], yy[unlist(simu.sta$l.T.mean) == median(unlist(simu.sta$l.T.mean))], yy[unlist(simu.sta$l.T.mean) == max(unlist(simu.sta$l.T.mean))] )

## Composites of SLP for year special year
SLP.lref.mean=c()
SLP.lref.std=c()
for(y in l.yref){
  ddum1=y*10000+1201
  ddum2=y*10000+1231
  SLP.lref.mean=cbind(SLP.lref.mean,apply(datNCEP$anom[datNCEP$time >= ddum1 & datNCEP$time <= ddum2,],2,mean))
  SLP.lref.std=cbind(SLP.lref.std,apply(datNCEP$anom[datNCEP$time >= ddum1 & datNCEP$time <= ddum2,],2,sd))
}


## Composites of SLP for the dynamical simulations,
SLP.lref.dyn.mean=c()
SLP.lref.dyn.std=c()
for(y in l.yref){
  sy=as.character(y)
  SLP.lref.dyn.std_loc = c()
  dates=c()
  for(i in 1:nsim){
    dates_loc = c()
    for(t in simu.dyn$l.X[[sy]][[i]][,1]){
      dates = cbind(dates,which(datNCEP$time==t))
      dates_loc = cbind(dates_loc,which(datNCEP$time==t))
    }
    SLP.lref.dyn.std_loc = cbind(SLP.lref.dyn.std_loc, apply(datNCEP$anom[dates_loc,],2,sd))
  }
  SLP.lref.dyn.mean=cbind(SLP.lref.dyn.mean,apply(datNCEP$anom[dates,],2,mean))
  SLP.lref.dyn.std=cbind(SLP.lref.dyn.std,apply(SLP.lref.dyn.std_loc,1,mean))
}

## Composites of SLP for the static simulations,
SLP.lref.sta.mean=c()
SLP.lref.sta.std=c()
for(y in l.yref){
  sy=as.character(y)
  SLP.lref.sta.std_loc = c()
  dates=c()
  for(i in 1:nsim){
    dates_loc = c()
    for(t in simu.sta$l.X[[sy]][[i]][,1]){
      dates = cbind(dates,which(datNCEP$time==t))
      dates_loc = cbind(dates_loc,which(datNCEP$time==t))
    }
    SLP.lref.sta.std_loc = cbind(SLP.lref.sta.std_loc, apply(datNCEP$anom[dates_loc,],2,sd))
  }
  SLP.lref.sta.mean=cbind(SLP.lref.sta.mean,apply(datNCEP$anom[dates,],2,mean))
  SLP.lref.sta.std=cbind(SLP.lref.sta.std,apply(SLP.lref.sta.std_loc,1,mean))
}

d.freq = as.data.frame(table(d.sta))
for(dd in d.freq[order(d.freq['Freq'], decreasing = T),][1:20,'d.sta']){
  print(paste(as.numeric(dd), T[which(T['Date']==as.numeric(dd)), 'RR_day'] ))
}

quantile(d.freq['Freq'][,1],c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1))

ZZ=unlist(simu.sta$l.T.mean)
XX=unlist(lapply(simu.sta$l.X.mean,median))
YY=unlist(lapply(simu.dyn$l.X.mean,median))
#correlation between the normal time series, and the simulated time series
#static simulations
cor.test(XX,ZZ)
#dynamic simulation
cor.test(YY,ZZ)

## Figure 4a
filout=paste(OUTdir,'plots/',gsub('.Rdat','_boxplotTS.pdf',filesim),sep="")
pdf(filout,width=7, height=5)
par(mar=c(4,4,1,1))
rangeplot=round(range(c(unlist(simu.sta$l.T.mean),
                        unlist(simu.dyn$l.X.mean), c(18)),na.rm=TRUE))
plot(c(yymin,yymax),rangeplot,type="n",xlab="Years",
     ylab=paste("December temperature [°C]"))
boxplot(simu.sta$l.X.mean,at=c(yymin:yymax)-0.2,
        add=TRUE,axes=FALSE,col="blue",outline=FALSE)
boxplot(simu.dyn$l.X.mean,at=c(yymin:yymax)+0.2,
        add=TRUE,axes=FALSE,col="red",outline=FALSE)
lines(c(yymin:yymax),unlist(simu.sta$l.T.mean))
abline(v=l.yref,lty=2,col=c("#0daebd","#79bd0d","#cfc461","#bf089b"))
text(l.yref,c(17.5,17.5,17.5,17.5), l.yref, col=c("#0daebd","#79bd0d","#cfc461","#bf089b"), bg=c('white','white','white','white'), srt=90)
legend("bottomleft",lwd=c(1,5,5),col=c("black","blue","red"),
       legend=c("Obs.","Static","Dynamic"),bty="n")
legend("topleft",legend=paste("a"))
dev.off()

## 5
legcol=c("#0daebd","#79bd0d","#cfc461","#bf089b")
filout=paste(OUTdir,'plots/',gsub('.Rdat','_patterns.pdf',filesim),sep="")
pdf(filout,width=12)
layout(matrix(1:12,3,4,byrow=TRUE))
k=1
for(j in 1:4){
  image.cont.c.ano(datNCEP$lon,datNCEP$lat,SLP.lref.mean[,j],
                   xlab="",ylab="",mar=c(3,3,1,1))
  legend("bottomleft",legend=l.yref[j],bg="white",text.col=legcol[j])
  legend("top",legend="Reanalysis",bg="white")
  legend("topleft",letters[k],bg="white")
  k=k+1
}
for(j in 1:4){
  image.cont.c.ano(datNCEP$lon,datNCEP$lat,SLP.lref.sta.mean[,j],
                   xlab="",ylab="",mar=c(3,3,1,1))
  legend("bottomleft",legend=l.yref[j],bg="white",text.col=legcol[j])
  legend("top",legend="Sta. Simulations",bg="white")
  legend("topleft",letters[k],bg="white")
  k=k+1
}
for(j in 1:4){
  image.cont.c.ano(datNCEP$lon,datNCEP$lat,SLP.lref.dyn.mean[,j],
                   xlab="",ylab="",mar=c(3,3,1,1))
  legend("bottomleft",legend=l.yref[j],bg="white",text.col=legcol[j])
  legend("top",legend="Dyn. Simulations",bg="white")
  legend("topleft",letters[k],bg="white")
  k=k+1
}
dev.off()


## number of cold days

## obs
cold_days.obs=list()
for(y in yymin:yymax){
  ddum1=y*10000+1201
  ddum2=y*10000+1231
  dates.loc = which(T$Date>=ddum1 & T$Date<=ddum2)
  cold_days.obs[[as.character(y)]]=sum(T$T_day[dates.loc] > 0 & T$T_day[dates.loc] < 10)
}



## sim
cold_days.sta=list()
cold_days.dyn=list()
for(y in yymin:yymax){
  sy=as.character(y)
  cold_days.sta.loc = c()
  cold_days.dyn.loc = c()
  for(i in 1:nsim){
    dates_loc = c()
    for(t in simu.sta$l.X[[sy]][[i]][,1]){
      dates_loc = cbind(dates_loc,which(T$Date==t))
    }
    cold_days.sta.loc = cbind(cold_days.sta.loc , sum(T$T_day[dates_loc] > 0 & T$T_day[dates_loc] < 10))
    dates_loc = c()
    for(t in simu.dyn$l.X[[sy]][[i]][,1]){
      dates_loc = cbind(dates_loc,which(T$Date==t))
    }
    cold_days.dyn.loc = cbind(cold_days.dyn.loc , sum(T$T_day[dates_loc] > 0 & T$T_day[dates_loc] < 10))
  }
  cold_days.sta[[sy]]=as.vector(cold_days.sta.loc)
  cold_days.dyn[[sy]]=as.vector(cold_days.dyn.loc)
}

## Figure 4b
filout=paste(OUTdir,'plots/',gsub('.Rdat','_cold-days_boxplotTS.pdf',filesim),sep="")
pdf(filout,width=7, height=5)
par(mar=c(4,4,1,1))
rangeplot=round(range(c(unlist(cold_days.obs),
                        unlist(cold_days.dyn),c(35)),na.rm=TRUE))
plot(c(yymin,yymax),rangeplot,type="n",xlab="Years",
     ylab=paste("number of cold days in December"))
boxplot(cold_days.sta,at=c(yymin:yymax)-0.2,
        add=TRUE,axes=FALSE,col="blue",outline=FALSE)
boxplot(cold_days.dyn,at=c(yymin:yymax)+0.2,
        add=TRUE,axes=FALSE,col="red",outline=FALSE)
lines(c(yymin:yymax),unlist(cold_days.obs))
abline(v=l.yref,lty=2,col=c("#0daebd","#79bd0d","#cfc461","#bf089b"))
text(l.yref,c(34,34,34,34), l.yref, col=c("#0daebd","#79bd0d","#cfc461","#bf089b"), bg=c('white','white','white','white'), srt=90)
#legend("bottomleft",lwd=c(1,5,5),col=c("black","blue","red"),
#       legend=c("Obs.","Static","Dynamic"),bty="n")
legend("topleft",legend=paste("b"))
dev.off()



#q("no")
