## Visualisations of extreme heatwaves generated by analogue based importance sampling
## Par Pascal Yiou (LSCE), Jan. 2019

base_dir="/Users/peterpfleiderer/Projects/analogues/" ## Needs to be adapted
setwd(paste(base_dir,'sim_data/',sep=''))

base_dir = "C:/Users/jason/OneDrive/Documents/GitHub/xtrem_precip_analogues/" ## Needs to be adapted
setwd(paste(base_dir,'sim_data/',sep=''))

search_strings = c('rr-m4d1nDay122_cal*_precip_0.5_N100-aggregNcum3-precipAprJul.Rdat', 'rr-m4d1nDay122_cal0.5_precip_*_N100-aggregNcum3-precipAprJul.Rdat', 'rr-m4d1nDay122_cal0.5_precip_0.5_N100-aggregNcum*-precipAprJul.Rdat')
variable_parameter = c('alpha.cal', 'alpha.var', 'nn')
xlabel = c('weight on calendar day', 'weight on precipitation', 'number of days before choosing a new analogue')


search_strings = c('rr-m4d1nDay122_cal0.5_precip_0.5_N100-aggregNcum*-precipAprJul.Rdat')
variable_parameter = c('nn')
xlabel = c('number of days before choosing a new analogue')

search_strings = c('rr-m4d1nDay122_cal0.5_precip_*_N100-aggregNcum5-precipAprJul.Rdat')
variable_parameter = c('alpha.var')
xlabel = c('weight on precipitation')

search_strings = c('rr-m4d1nDay122_cal*_precip_0.5_N100-aggregNcum5-precipAprJul.Rdat')
variable_parameter = c('alpha.cal')
xlabel = c('weight on calendar day')

for (version in c(1)){
    
    list.in = system(paste("ls ",search_strings[version],sep=""),intern=TRUE)

    ## Data input
    i=1
    l.alpha=c()
    Tobs=list()
    Tsimdyn=list()
    Tsimsta=list()
    Prob_simdyn=list()
    Prob_simsta=list()
    for(filin in list.in){
        load(filin)
        
        if (variable_parameter[version] == 'alpha.cal'){
            l.alpha[[i]]=alpha.cal
            title = paste('fixed alpha.var:',alpha.var, 'fixed number of days:', strsplit(strsplit(filin,'-precip')[[1]][1], 'Ncum')[[1]][2],sep=' ')
        } else if(variable_parameter[version] == 'alpha.var') {
            l.alpha[[i]]=alpha.var
            title = paste('fixed alpha.cal:',alpha.cal, 'fixed number of days:', strsplit(strsplit(filin,'-precip')[[1]][1], 'Ncum')[[1]][2],sep=' ')
        } else if(variable_parameter[version] == 'nn') {
            l.alpha[[i]]= as.integer(strsplit(strsplit(filin,'-precip')[[1]][1], 'Ncum')[[1]][2])
            title = paste('fixed alpha.cal:',alpha.cal, 'fixed alpha.var:',alpha.var ,sep=' ')
            # l.alpha = 1:5
        }
        
        Tobs=unlist(simu.dyn$l.varIN.mean) #* 30
        Tsimdyn[[i]]=unlist(simu.dyn$l.X.mean) #*30
        Tsimsta[[i]]=unlist(simu.sta$l.X.mean) #*30
        Prob_simdyn[[i]]=unlist(simu.dyn$Prob.sim) #*30
        Prob_simsta[[i]]=unlist(simu.sta$Prob.sim) #*30
        i=i+1
    }
    
    l.alpha.order = order(l.alpha)
    l.alpha = sort(l.alpha)
    
    sd.obs=sd(Tobs)
    m.obs=mean(Tobs)

    proba.RTdyn=c()
    proba.RTsta=c()
    for(i in 1:length(l.alpha)){
        dum=1-pnorm(mean(Tsimdyn[[i]]),mean=m.obs,sd=sd.obs)
        proba.RTdyn=c(proba.RTdyn,dum)
        dum=1-pnorm(mean(Tsimsta[[i]]),mean=m.obs,sd=sd.obs)
        proba.RTsta=c(proba.RTsta,dum)
    }
    
    l.proba=1-pnorm(c(20:24),mean=m.obs,sd=sd.obs)
    l.probs=c(1,0.5,0.7,0.9,0.99,0.99999)
    Tdum=qnorm(l.probs,mean=m.obs,sd=sd.obs)
    
    ## Figure 4 of Y&J
    filout=paste('../plots/',search_strings[version],".png",sep="")
    png(filename=filout,width=1500,height=1500,units = "px", pointsize = 40, bg = "white", res = NA)
    default_marges=c(5.1,4.1,4.1,2.1)
    par(mar=default_marges + c(0, 1, -1, 0), cex.axis = 1, cex.lab  = 1.5)
    boxwex = (max(l.alpha) - min(l.alpha))/length(l.alpha)
    plot(c(1-0.3,length(l.alpha)+0.3),c(0,12), xaxt = "n", type="n", xlab=xlabel[version], ylab="April - July precipitation [mm/day]",axes=FALSE, main=title)
    abline(h=Tobs["2016"],lty=3,lwd=4)
    boxplot(Tobs,add=TRUE,boxwex=boxwex,at=-0.1, lwd=4)
    for(i in 1:length(l.alpha)){
        boxplot(Tsimdyn[l.alpha.order[i]],at=i-boxwex*0.1,axes=FALSE,add=TRUE,
                col="red",boxwex=boxwex, lwd=4)
        boxplot(Tsimsta[l.alpha.order[i]],at=i+boxwex*0.1,axes=FALSE,add=TRUE,
                col="blue",boxwex=boxwex, lwd=4)
    }
    axis(side=1, at=1:length(l.alpha), labels=l.alpha,lwd=4)
    axis(side=2,lwd=4)
    axis(side=4,at=Tdum,labels=round(1/(1-l.probs)),lwd=4)
    ##axis(side=3,at=l.alpha,labels=round(1/proba.RTsta))
    box()
    dev.off()
}


