## Visualisations of extreme heatwaves generated by analogue based importance sampling
## Par Pascal Yiou (LSCE), Jan. 2019

OUTdir=""

## Circulation reanalyses datasets (SLP, Z500, Z500 detrended)
## SLP: slp.1948-2018_NA.nc
## Z500: hgt.1948-2018_NA.nc
## Z500 detrended: base_z500_1950-01-01_2018-12-31_-80.0_50.0_20.0_70.0.nc
library(ncdf4)

source("scripts/_useful_functions.R")
source("scripts/_plotting_functions.R")

## Simulations
filesim="rr-m4d1nDay122_cal0.5_precip_0.5_N1000-aggregNcum5-precipAprJul.Rdat"
varname="rr"

##for(filin in list.in){
print(paste("Processing",filesim))
load(paste('sim_data/',filesim,sep=''))

print(args_tmp)

varname = args_tmp[1] ## args_tmp is written with load(filin)!
Lsim =as.integer(args_tmp[2])
mo.start =as.integer(args_tmp[3])
day.start =as.integer(args_tmp[4])
nsim =as.integer(args_tmp[5])
yymin=as.integer(args_tmp[6])
yymax=as.integer(args_tmp[7])
jobid=args_tmp[9]
alpha = args_tmp[10]
alpha.cal = args_tmp[11]
nn = args_tmp[12]

yy=yymin:yymax

filout=paste(OUTdir,'plots/',gsub('.Rdat','_repetitions.pdf',filesim),sep="")
pdf(filout,width=12)
layout(matrix(1:8,2,4,byrow=TRUE))
k=1
quantiles = c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)
for(style in c('dyn','sta')){
  for(y in l.yref){
    sy=as.character(y)
    freqs.tmp = c()
    for(i in 1:nsim){
      if(style == 'dyn'){
        d.ref=simu.dyn$l.X[[sy]][[i]][,1]
      } else{
        d.ref=simu.sta$l.X[[sy]][[i]][,1]
      }
      d.freq = as.data.frame(table(d.ref))
      freqs.tmp = rbind(freqs.tmp,quantile(d.freq['Freq'][,1],quantiles))
    }
    plot(c(0,100),c(0,12),type="n",xlab="percentile of most repeated dates", ylab="number of repetitions",axes=T, main=sy)
    boxplot(freqs.tmp,at=quantiles*100,add=T,axes=F,col="red", boxwex=5)
    legend("top",legend=paste(style," Simulations"),bg="white")
    legend("topleft",letters[k],bg="white")
    k=k+1
  }
}
dev.off()

# Figure A7

filout=paste(OUTdir,'plots/',gsub('.Rdat','_repetitionTS.pdf',filesim),sep="")
pdf(filout,width=12)
k=1
quantiles = c(1)
plot(c(yymin,yymax),c(0,12),type="n",xlab="year", ylab="maximal number of repetitions of a single date",axes=T,main=paste('alpha',alpha.TN,'alpha.cal',alpha.cal,'nn',nn,sep=" "))
styles = c('dyn','sta')
colors = c('red','blue')
shifts = c(-0.2,0.2)
for(sty in 1:2){
  for(y in yymin:yymax){
    sy=as.character(y)
    freqs.tmp = c()
    for(i in 1:nsim){
      if(styles[sty] == 'dyn'){
        d.ref=simu.dyn$l.X[[sy]][[i]][,1]
      } else{
        d.ref=simu.sta$l.X[[sy]][[i]][,1]
      }
      d.freq = as.data.frame(table(d.ref))
      freqs.tmp = rbind(freqs.tmp,quantile(d.freq['Freq'][,1],quantiles))
    }
    boxplot(freqs.tmp,at=c(y+shifts[sty]),add=T,axes=F,col=colors[sty], boxwex=1)
    k=k+1
  }
}
dev.off()


#
