## Visualisations of extreme heatwaves generated by analogue based importance sampling
## Par Pascal Yiou (LSCE), Jan. 2019

OUTdir=""

## Circulation reanalyses datasets (SLP, Z500, Z500 detrended)
## SLP: slp.1948-2018_NA.nc
## Z500: hgt.1948-2018_NA.nc
## Z500 detrended: base_z500_1950-01-01_2018-12-31_-80.0_50.0_20.0_70.0.nc
library(ncdf4)

source("_useful_functions.R")
source("_plotting_functions.R")

## Simulations
filesim="rr-m4d1nDay122_cal0.5_precip_0.5_N1000-aggregNcum5-precipAprJul.Rdat"
varname="rr"

## Data recuperation
load(paste(OUTdir,'plots/',gsub('.Rdat','_prepd.Rdat',filesim),sep=""))

## Figure 6
filout=paste(OUTdir,'plots/',gsub('.Rdat','_boxplotTS.pdf',filesim),sep="")
pdf(filout,width=7, height=5)
par(mar=c(4,4,1,1))
rangeplot=round(range(c(unlist(simu.sta$l.varIN.mean),
                        unlist(simu.dyn$l.X.mean), c(7.5)),na.rm=TRUE))
plot(c(yymin,yymax),rangeplot,type="n",xlab="Years",
     ylab=paste("mean daily precipitation [mm]"))
boxplot(simu.sta$l.X.mean,at=c(yymin:yymax)-0.2,
        add=TRUE,axes=FALSE,col="blue",outline=FALSE)
boxplot(simu.dyn$l.X.mean,at=c(yymin:yymax)+0.2,
        add=TRUE,axes=FALSE,col="red",outline=FALSE)
lines(c(yymin:yymax),unlist(simu.sta$l.varIN.mean))
abline(v=l.yref,lty=2,col=c("#0daebd","#79bd0d","#cfc461","#bf089b"))
text(l.yref,c(7.5,7.5,7.5,7.5), l.yref, col=c("#0daebd","#79bd0d","#cfc461","#bf089b"), bg=c('white','white','white','white'), srt=90)
legend("topleft",lwd=c(1,5,5),col=c("black","blue","red"),
       legend=c("Obs.","Static","Dynamic"),bty="n", bg='white')
dev.off()



## Figure 7
legcol=c("#0daebd","#79bd0d","#cfc461","#bf089b")
filout=paste(OUTdir,'plots/',gsub('.Rdat','_patterns.pdf',filesim),sep="")
pdf(filout,width=12)
layout(matrix(1:12,3,4,byrow=TRUE))
k=1
for(j in 1:4){
  image.cont.c.ano(datNCEP$lon,datNCEP$lat,SLP.lref.mean[,j],
                 xlab="",ylab="",mar=c(3,3,1,1))
  legend("bottomleft",legend=l.yref[j],bg="white",text.col=legcol[j])
  legend("top",legend="Reanalysis",bg="white")
  legend("topleft",letters[k],bg="white")
  k=k+1
}
for(j in 1:4){
  image.cont.c.ano(datNCEP$lon,datNCEP$lat,SLP.lref.sta.mean[,j],
                 xlab="",ylab="",mar=c(3,3,1,1))
  legend("bottomleft",legend=l.yref[j],bg="white",text.col=legcol[j])
  legend("top",legend="Sta. Simulations",bg="white")
  legend("topleft",letters[k],bg="white")
  k=k+1
}
for(j in 1:4){
  image.cont.c.ano(datNCEP$lon,datNCEP$lat,SLP.lref.dyn.mean[,j],
                 xlab="",ylab="",mar=c(3,3,1,1))
  legend("bottomleft",legend=l.yref[j],bg="white",text.col=legcol[j])
  legend("top",legend="Dyn. Simulations",bg="white")
  legend("topleft",letters[k],bg="white")
  k=k+1
}
dev.off()

## Figure B1
legcol=c("#0daebd","#79bd0d","#cfc461","#bf089b")
filout=paste(OUTdir,'plots/',gsub('.Rdat','_patternSTD_interannual.pdf',filesim),sep="")

pdf(filout,width=12)
layout(matrix(1:12,3,4,byrow=TRUE))
k=1
for(j in 1:4){
  image.cont.c.ano(datNCEP$lon,datNCEP$lat,SLP.lref.std[,j],
               xlab="",ylab="",mar=c(3,3,1,1))
  legend("bottomleft",legend=l.yref[j],bg="white",text.col=legcol[j])
  legend("top",legend="Reanalysis",bg="white")
  legend("topleft",letters[k],bg="white")
  k=k+1
}

for(j in 1:4){
  image.cont.c.ano(datNCEP$lon,datNCEP$lat,SLP.lref.sta.std[,j],
               xlab="",ylab="",mar=c(3,3,1,1))
  legend("bottomleft",legend=l.yref[j],bg="white",text.col=legcol[j])
  legend("top",legend="Sta. Simulations",bg="white")
  legend("topleft",letters[k],bg="white")
  k=k+1
}

for(j in 1:4){
  image.cont.c.ano(datNCEP$lon,datNCEP$lat,SLP.lref.dyn.std[,j],
               xlab="",ylab="",mar=c(3,3,1,1))
  legend("bottomleft",legend=l.yref[j],bg="white",text.col=legcol[j])
  legend("top",legend="Dyn. Simulations",bg="white")
  legend("topleft",letters[k],bg="white")
  k=k+1
}

dev.off()




##}



#q("no")
